### ISSUE TITLE
feature request: move the icon to address bar

### ISSUE THREAD

**Issue by rezad1393** [lilydjwg/cf-pop#1]
Can You move the icon from toolbar to address bar?
and show it only when cloudflare is detected?
this way it takes less space and is more smooth.

**Comment by lilydjwg** [comment]
This is a good idea, except that I need to draw the badge text myself.

**Comment by lilydjwg** [comment]
I give up. The toolbar icon is 28x32 while the urlbar icon is only 16x16 (there is a big margin). Too small to see the text.

**Comment by lilydjwg** [comment]
This is what I've achieved. Just compare the size with the uBlock Origin's text.

![图片](https://user-images.githubusercontent.com/440661/97084918-b7171180-164c-11eb-870e-5b81afa7d80a.png)

**Comment by rezad1393** [comment]
maybe only show it in urlbar when cloudflare is  detected and then show the datacenter as a popup text?

**Comment by lilydjwg** [comment]
But the whole point of this extension is to show the datacenter. Maybe get rid of the cloud?

**Comment by rezad1393** [comment]
I dont understand what you mean by "Maybe get rid of the cloud?"
you say that text in ulrbar icon(actually the whole icon ) is too small to show the data-center text, so I thought maybe just show the icon "when cloudflare is detected and then show the data-center as a popup text?"

**Comment by lilydjwg** [comment]
I mean the Cloudflare logo. The datacenter code needs to be visible as one browses, because that's why I develop this addon.

**Comment by rezad1393** [comment]
ok
